package com.keynumber.folino.settings

import org.swift.swiftkit.core.SwiftMemoryManagement
import com.keynumber.folino.settings.swiftjava.Data as SwiftData
import com.keynumber.folino.settings.swiftjava.FolinoSettingsJNI as SwiftJavaJNI

/**
 * Thin façade over the JNI entry point generated by swift-java's
 * JExtractSwiftPlugin from `Sources/SettingsLogic` (staged under
 * `src/main/java-generated/`).
 *
 * `libFolinoSettingsJNI.so` and its dependencies (libSwiftJava.so, the
 * Swift runtime) load via the generated [SwiftJavaJNI]'s static
 * initialiser the first time [nativeLoadVersionHistory] resolves the
 * class.
 */
object SettingsJNI {

    /**
     * Hands the raw `VersionHistory.yml` bytes to Swift, which decodes
     * them, resolves localized descriptions, and re-encodes the result as
     * a wirelet-format `VersionHistoryWireList` payload. Returns the
     * encoded bytes (decode via [VersionHistoryWireListCodec]).
     */
    fun nativeLoadVersionHistory(ymlBytes: ByteArray): ByteArray {
        val arena = SwiftMemoryManagement.DEFAULT_SWIFT_JAVA_AUTO_ARENA
        return SwiftJavaJNI.nativeLoadVersionHistory(SwiftData.fromByteArray(ymlBytes, arena), arena).toByteArray()
    }

    /**
     * Whether cold launch number [coldLaunchCount] (1-based) is one where the review prompt should be
     * shown, per the shared `Domain.ReviewPromptCadence` — the same schedule iOS uses, so neither
     * platform re-derives "how often do we ask". Counting the launches and invoking Play's review flow
     * stay on this side.
     */
    fun nativeShouldPromptForReview(coldLaunchCount: Int): Boolean =
        SwiftJavaJNI.nativeShouldPromptForReview(coldLaunchCount)
}
