plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
    id("io.github.jiyimeta.wirelet") version "0.3.2"
    id("com.google.devtools.ksp") version "2.0.20-1.0.25"
}

android {
    namespace = "com.keynumber.folino.reader"
    compileSdk = 35

    defaultConfig {
        minSdk = 28
        ndk { abiFilters += listOf("arm64-v8a", "x86_64") }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = "17" }

    buildFeatures { compose = true }

    // Prebuilt libFolinoReaderJNI.so + libSwiftJava.so + Swift runtime live here,
    // staged by Scripts/android-build-reader-libs.sh before any Gradle task that
    // consumes them. swift-java jextract output (Java bindings) is staged into
    // src/main/java-generated by the same script. Both dirs are gitignored.
    sourceSets["main"].jniLibs.srcDirs("src/main/jniLibs")
    sourceSets["main"].java.srcDirs("src/main/java-generated")
}

dependencies {
    val composeBom = platform("androidx.compose:compose-bom:2024.09.02")
    implementation(composeBom)
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.compose.ui:ui-tooling-preview")
    // BackHandler, for ending an edit session on the system back gesture (matches :app's version).
    implementation("androidx.activity:activity-compose:1.9.2")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.8.7")

    implementation("androidx.media3:media3-session:1.5.0")
    implementation("androidx.media3:media3-common:1.5.0")
    implementation("androidx.media:media:1.7.0")

    // androidx.ink 1.0.0 (Apache-2.0): wet capture (authoring, View-based), dry render (rendering), brush, geometry.
    implementation("androidx.ink:ink-strokes:1.0.0")
    implementation("androidx.ink:ink-brush:1.0.0")
    implementation("androidx.ink:ink-brush-compose:1.0.0")
    implementation("androidx.ink:ink-authoring:1.0.0")
    implementation("androidx.ink:ink-rendering:1.0.0")
    implementation("androidx.ink:ink-geometry:1.0.0")
    // Low-latency motion prediction for wet capture (separate artifact group, Apache-2.0).
    implementation("androidx.input:input-motionprediction:1.0.0")

    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")

    // Wirelet runtime + observable runtime backing the generated annotation bridges:
    // the @WireletProvided `AnnotationPersistenceStore` interface + native adapter and the
    // @WireletObservable `AnnotationSaveBridgeViewModel`. Codegen is wired below.
    api("io.github.jiyimeta:wirelet-runtime:0.3.2")
    api("io.github.jiyimeta:wirelet-observable-runtime:0.3.2")

    // Room-backed annotation_layers store implementing the generated
    // AnnotationPersistenceStore interface (per-score annotation-layer blobs).
    implementation("androidx.room:room-runtime:2.6.1")
    ksp("androidx.room:room-compiler:2.6.1")

    // Soundfont download bridge: the reader playback service prefers the downloaded high-quality SF2
    // and hot-swaps the engine onto it via SoundfontController + the generated store view model.
    implementation(project(":FolinoSoundfontAndroid"))

    // The edit session (SP3): the relay, its host contract, and the generated bridge. The Reader owns the
    // score handle the mirror session lives beside, so it is what implements EditSessionHost.
    api(project(":FolinoEditorAndroid"))

    // Runtime support for the swift-java-generated bindings under java-generated/
    // (FolinoReaderJNI → shared Domain scroll-follow logic). Locally published to
    // mavenLocal from Packages/Features/Settings/.build/checkouts/swift-java.
    implementation("org.swift.swiftkit:swiftkit-core:1.0-SNAPSHOT")

    // swift-sheet-music Android libraries (mavenLocal). Version is property-driven
    // (see gradle.properties `ssmVersion`); pass -PssmVersion=0.0.0-<branch>-SNAPSHOT
    // to consume a parallel ssm worktree's branch publish. Keep all on one version.
    val ssmVersion = (findProperty("ssmVersion") as String?) ?: "0.0.0-SNAPSHOT"
    implementation("io.github.jiyimeta:sheet-music-compose-android:$ssmVersion")
    implementation("io.github.jiyimeta:sheet-music-audio-android:$ssmVersion")
    implementation("io.github.jiyimeta:sheet-music-android:$ssmVersion")

    testImplementation("junit:junit:4.13.2")
}

val packageRoot: File = rootProject.projectDir.resolve("..").canonicalFile

wirelet {
    val readerCheckout = packageRoot.resolve("Packages/Features/Reader/.build/checkouts/swift-wirelet")
    val rootCheckout = packageRoot.resolve(".build/checkouts/swift-wirelet")
    swiftPackagePath.set(if (readerCheckout.exists()) readerCheckout else rootCheckout)

    sources {
        register("main") {
            schemaPaths.from(packageRoot.resolve("Packages/Features/Reader/Sources/FolinoReaderJNI"))
            codecPackage.set("com.keynumber.folino.reader")
            modelPackage.set("com.keynumber.folino.reader")
            emitModels.set(true)
        }
    }
    observable {
        register("main") {
            schemaPaths.from(packageRoot.resolve("Packages/Features/Reader/Sources/FolinoReaderJNI"))
            viewModelPackage.set("com.keynumber.folino.reader.generated")
            modelPackage.set("com.keynumber.folino.reader")
            codecPackage.set("com.keynumber.folino.reader")
            libraryName.set("FolinoReaderJNI")
            providedAdapterPackage.set("com.keynumber.folino.reader")
        }
    }
    provided {
        register("main") {
            schemaPaths.from(packageRoot.resolve("Packages/Features/Reader/Sources/FolinoReaderJNI"))
            interfacePackage.set("com.keynumber.folino.reader")
            adapterPackage.set("com.keynumber.folino.reader")
            modelPackage.set("com.keynumber.folino.reader")
            codecPackage.set("com.keynumber.folino.reader")
        }
    }
}

// kotlin.android needs the generated dirs wired manually (the plugin hooks
// kotlin.jvm only). Mirror the Library module's pattern for the codec task,
// the observable viewmodel task, AND the provided-interface task.
val generateCodecs = tasks.named("generateWireletCodecsMain")
val generateViewModels = tasks.named("generateWireletObservableViewModelsMain")
val generateProvided = tasks.named("generateWireletProvidedInterfacesMain")

android {
    sourceSets["main"].kotlin.srcDir(
        generateCodecs.flatMap { (it as io.github.jiyimeta.wirelet.gradle.GenerateWireletCodecs).outputDir }
    )
    sourceSets["main"].kotlin.srcDir(
        generateViewModels.flatMap { (it as io.github.jiyimeta.wirelet.gradle.GenerateWireletObservableViewModels).outputDir }
    )
    sourceSets["main"].kotlin.srcDir(
        generateProvided.flatMap { (it as io.github.jiyimeta.wirelet.gradle.GenerateWireletProvidedInterfaces).outputDir }
    )
}

tasks.matching { it.name.startsWith("compile") && it.name.endsWith("Kotlin") }
    .configureEach { dependsOn(generateCodecs, generateViewModels, generateProvided) }
