plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
    id("io.github.jiyimeta.wirelet") version "0.3.2"
}

android {
    namespace = "com.keynumber.folino.editor"
    compileSdk = 35

    defaultConfig {
        minSdk = 28
        ndk { abiFilters += listOf("arm64-v8a", "x86_64") }
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = "17" }

    // EditSessionRelay logs on its resync path (android.util.Log, unmocked on the JVM); JVM unit tests need
    // Log calls to no-op rather than throw so EditSessionRelayTest can exercise that path off-device.
    testOptions { unitTests.isReturnDefaultValues = true }

    // Prebuilt libFolinoEditorJNI.so + libSwiftJava.so + Swift runtime live here,
    // staged by Scripts/android-build-editor-libs.sh before any Gradle task that
    // consumes them. swift-java jextract output (Java bindings) is staged into
    // src/main/java-generated by the same script. Both dirs are gitignored.
    sourceSets["main"].jniLibs.srcDirs("src/main/jniLibs")
    sourceSets["main"].java.srcDirs("src/main/java-generated")
}

dependencies {
    // Wirelet runtime + observable runtime backing the generated annotation bridges:
    // the @WireletProvided `EditorHostFiles` interface + native adapter and the
    // @WireletObservable `EditorBridgeViewModel`. Codegen is wired below.
    api("io.github.jiyimeta:wirelet-runtime:0.3.2")
    api("io.github.jiyimeta:wirelet-observable-runtime:0.3.2")
    // The generated EditorBridgeViewModel extends ViewModel and uses viewModelScope + StateFlow
    // to publish the projection — same pattern as FolinoLibraryAndroid / FolinoSoundfontAndroid.
    api("androidx.lifecycle:lifecycle-viewmodel:2.8.7")
    api("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0")

    // Runtime support for the swift-java-generated bindings under java-generated/
    // (FolinoEditorJNI → shared EditorCore editing session). Locally published to
    // mavenLocal from Packages/Features/Settings/.build/checkouts/swift-java.
    implementation("org.swift.swiftkit:swiftkit-core:1.0-SNAPSHOT")

    // swift-sheet-music Android libraries (mavenLocal). Version is property-driven
    // (see gradle.properties `ssmVersion`); pass -PssmVersion=0.0.0-<branch>-SNAPSHOT
    // to consume a parallel ssm worktree's branch publish. Keep all on one version.
    val ssmVersion = (findProperty("ssmVersion") as String?) ?: "0.0.0-SNAPSHOT"
    implementation("io.github.jiyimeta:sheet-music-compose-android:$ssmVersion")
    implementation("io.github.jiyimeta:sheet-music-audio-android:$ssmVersion")
    implementation("io.github.jiyimeta:sheet-music-android:$ssmVersion")

    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.2.1")
    androidTestImplementation("androidx.test:runner:1.6.2")
}

val packageRoot: File = rootProject.projectDir.resolve("..").canonicalFile

wirelet {
    val editorCheckout = packageRoot.resolve("Packages/Features/Editor/.build/checkouts/swift-wirelet")
    val rootCheckout = packageRoot.resolve(".build/checkouts/swift-wirelet")
    swiftPackagePath.set(if (editorCheckout.exists()) editorCheckout else rootCheckout)

    sources {
        register("main") {
            schemaPaths.from(packageRoot.resolve("Packages/Features/Editor/Sources/FolinoEditorJNI"))
            codecPackage.set("com.keynumber.folino.editor")
            modelPackage.set("com.keynumber.folino.editor")
            emitModels.set(true)
        }
    }
    observable {
        register("main") {
            schemaPaths.from(packageRoot.resolve("Packages/Features/Editor/Sources/FolinoEditorJNI"))
            viewModelPackage.set("com.keynumber.folino.editor.generated")
            modelPackage.set("com.keynumber.folino.editor")
            codecPackage.set("com.keynumber.folino.editor")
            libraryName.set("FolinoEditorJNI")
            providedAdapterPackage.set("com.keynumber.folino.editor")
        }
    }
    provided {
        register("main") {
            schemaPaths.from(packageRoot.resolve("Packages/Features/Editor/Sources/FolinoEditorJNI"))
            interfacePackage.set("com.keynumber.folino.editor")
            adapterPackage.set("com.keynumber.folino.editor")
            modelPackage.set("com.keynumber.folino.editor")
            codecPackage.set("com.keynumber.folino.editor")
        }
    }
}

// kotlin.android needs the generated dirs wired manually (the plugin hooks
// kotlin.jvm only). Mirror the Reader module's pattern for the codec task,
// the observable viewmodel task, AND the provided-interface task.
val generateCodecs = tasks.named("generateWireletCodecsMain")
val generateViewModels = tasks.named("generateWireletObservableViewModelsMain")
val generateProvided = tasks.named("generateWireletProvidedInterfacesMain")

android {
    sourceSets["main"].kotlin.srcDir(
        generateCodecs.flatMap { (it as io.github.jiyimeta.wirelet.gradle.GenerateWireletCodecs).outputDir }
    )
    sourceSets["main"].kotlin.srcDir(
        generateViewModels.flatMap { (it as io.github.jiyimeta.wirelet.gradle.GenerateWireletObservableViewModels).outputDir }
    )
    sourceSets["main"].kotlin.srcDir(
        generateProvided.flatMap { (it as io.github.jiyimeta.wirelet.gradle.GenerateWireletProvidedInterfaces).outputDir }
    )
}

tasks.matching { it.name.startsWith("compile") && it.name.endsWith("Kotlin") }
    .configureEach { dependsOn(generateCodecs, generateViewModels, generateProvided) }
