import SwiftUI
import UIKit

// DRUM-ICON-DATA:BEGIN — everything to the END marker is generated by Scripts/generate-drum-icons.py from
// Scripts/drum-icons.json. Edit the drawings there (or in pen.dev and then there), never here.
//
// The path data is normalized to absolute move / line / cubic / close, so nothing below has to do arc maths.

/// One drum-kit instrument drawn the way the instrument actually looks, for the note-entry pad's key faces.
///
/// Deliberately not SMuFL: the percussion pictograms in Bravura are notation symbols meant to sit above a staff
/// beside a written instrument name — a tom-tom is a plain square, a suspended cymbal a horizontal line — and at a
/// 44 pt key they carry no information. These are drawn from the hardware instead: counterhoop, head, lugs, legs,
/// stand, pedal, cymbal bell.
///
/// Cymbals are told apart by size and tilt rather than by a label: the ride is flat and largest, and the two
/// crashes are mirror images so the tilt says which side of the kit the cymbal is on. Toms are told apart by the
/// letter on the shell, which `EditorDrumPadRows` supplies only when the pad actually holds more than one of that
/// kind (`labelAnchor`).
enum DrumInstrumentIcon: CaseIterable, Sendable {
    case hiHatClosed
    case hiHatOpen
    case hiHatPedal
    case crashLeft
    case crashRight
    case ride
    case cowbell
    case snare
    case sideStick
    case tom
    case floorTom
    case kick

    /// The icon for a GM drum pitch, or `nil` for one nothing is drawn for — the pad falls back to the notehead
    /// glyph and short name there, which is what a user-edited layout holding a tambourine or a bongo gets.
    static func forPitch(_ pitch: Int) -> DrumInstrumentIcon? {
        switch pitch {
        case 35: .kick
        case 36: .kick
        case 37: .sideStick
        case 38: .snare
        case 40: .snare
        case 41: .floorTom
        case 42: .hiHatClosed
        case 43: .floorTom
        case 44: .hiHatPedal
        case 45: .tom
        case 46: .hiHatOpen
        case 47: .tom
        case 48: .tom
        case 49: .crashLeft
        case 50: .tom
        case 51: .ride
        case 56: .cowbell
        case 57: .crashRight
        default: nil
        }
    }

    /// The design-space rectangle the path data is drawn in. Each icon has its own, chosen so the drawing sits
    /// centred and fills its key by the amount its real-world size deserves — the ride fills 96% of the frame, a
    /// crash 82% of that, a rack tom 71%.
    var viewBox: CGRect {
        switch self {
        case .hiHatClosed: CGRect(x: 10.5, y: 12, width: 79, height: 79)
        case .hiHatOpen: CGRect(x: 10.5, y: 12, width: 79, height: 79)
        case .hiHatPedal: CGRect(x: 10.5, y: 28, width: 79, height: 79)
        case .crashLeft: CGRect(x: -7.15, y: -5.15, width: 114.3, height: 114.3)
        case .crashRight: CGRect(x: -7.15, y: -5.15, width: 114.3, height: 114.3)
        case .ride: CGRect(x: 2.1, y: 4.1, width: 95.8, height: 95.8)
        case .cowbell: CGRect(x: -2.15, y: -4.65, width: 104.3, height: 104.3)
        case .snare: CGRect(x: 3.35, y: -3.65, width: 93.3, height: 93.3)
        case .sideStick: CGRect(x: 3.35, y: -4.34, width: 93.3, height: 93.3)
        case .tom: CGRect(x: 3.7, y: 0.4, width: 92.6, height: 92.6)
        case .floorTom: CGRect(x: 3.7, y: 4.2, width: 92.6, height: 92.6)
        case .kick: CGRect(x: 10.4, y: 4.4, width: 79.2, height: 79.2)
        }
    }

    // The path data below is generated and each drawing is one literal. Wrapping it would not make it readable,
    // only harder to replace wholesale the next time a drawing changes.
    // swiftlint:disable line_length

    /// The outline — the instrument itself.
    var strokePath: String {
        switch self {
        case .hiHatClosed: "M16 60L42 52C44 46 56 46 58 52L84 60M16 60L38 67C46 69.55 54 69.55 62 67L84 60M84 60C62 64.2 38 64.2 16 60M50 46L50 36M50 68.9L50 79"
        case .hiHatOpen: "M16 48L42 40C44 34 56 34 58 40L84 48M84 48C62 52.2 38 52.2 16 48M16 60L38 67C46 69.55 54 69.55 62 67L84 60M84 60C62 55.03 38 55.03 16 60M50 34L50 24M50 51.15L50 60M50 68.9L50 79"
        case .hiHatPedal: "M16 60L42 52C44 46 56 46 58 52L84 60M16 60L38 67C46 69.55 54 69.55 62 67L84 60M84 60C62 64.2 38 64.2 16 60M50 46L50 36M50 68.9L50 90"
        case .crashLeft: "M95 61.6C94.13 65.43 84.75 67.15 70.4 66.09C56.04 65.04 38.89 61.38 25.4 56.49C11.91 51.61 4.13 46.23 5 42.4C5.87 38.57 15.25 36.85 29.6 37.91C43.96 38.96 61.11 42.62 74.6 47.51C88.09 52.39 95.87 57.77 95 61.6M53.1 48.3L48.7 47.4M66.1 60.7C56.1 60 40.8 56.7 31.7 53.4"
        case .crashRight: "M5 61.6C5.87 65.43 15.25 67.15 29.6 66.09C43.96 65.04 61.11 61.38 74.6 56.49C88.09 51.61 95.87 46.23 95 42.4C94.13 38.57 84.75 36.85 70.4 37.91C56.04 38.96 38.89 42.62 25.4 47.51C11.91 52.39 4.13 57.77 5 61.6M46.9 48.3L51.3 47.4M33.9 60.7C43.9 60 59.2 56.7 68.3 53.4"
        case .ride: "M4 52C4 58.08 24.59 63 50 63C75.41 63 96 58.08 96 52C96 45.92 75.41 41 50 41C24.59 41 4 45.92 4 52M47.77 47.79L50 47.79L52.23 47.79M32.4 57.14C42.41 58.52 58.04 58.52 67.6 57.14"
        case .cowbell: "M38 16L62 16L76 74L24 74ZM24 74L28 84L72 84L76 74M46 16L46 11L54 11L54 16"
        case .snare: "M10 28C10 34.63 27.91 40 50 40C72.09 40 90 34.63 90 28C90 21.37 72.09 16 50 16C27.91 16 10 21.37 10 28M15 28C15 33.25 30.67 37.5 50 37.5C69.33 37.5 85 33.25 85 28C85 22.75 69.33 18.5 50 18.5C30.67 18.5 15 22.75 15 28M10 28L10 58C10 64.63 27.91 70 50 70C72.09 70 90 64.63 90 58L90 28M10 54C10 60.63 27.91 66 50 66C72.09 66 90 60.63 90 54"
        case .sideStick: "M10 28C10 34.63 27.91 40 50 40C72.09 40 90 34.63 90 28C90 21.37 72.09 16 50 16C27.91 16 10 21.37 10 28M15 28C15 33.25 30.67 37.5 50 37.5C69.33 37.5 85 33.25 85 28C85 22.75 69.33 18.5 50 18.5C30.67 18.5 15 22.75 15 28M10 28L10 58C10 64.63 27.91 70 50 70C72.09 70 90 64.63 90 58L90 28M10 54C10 60.63 27.91 66 50 66C72.09 66 90 60.63 90 54M32.47 31.64L90 14.63"
        case .tom: "M18 32C18 38.08 32.33 43 50 43C67.67 43 82 38.08 82 32C82 25.92 67.67 21 50 21C32.33 21 18 25.92 18 32M23 32C23 36.69 35.09 40.5 50 40.5C64.91 40.5 77 36.69 77 32C77 27.31 64.91 23.5 50 23.5C35.09 23.5 23 27.31 23 32M18 32L18 68.3C18 74.38 32.33 79.3 50 79.3C67.67 79.3 82 74.38 82 68.3L82 32M18 64.3C18 70.38 32.33 75.3 50 75.3C67.67 75.3 82 70.38 82 64.3M50 22L50 14M43 14L57 14"
        case .floorTom: "M14 19C14 25.63 30.12 31 50 31C69.88 31 86 25.63 86 19C86 12.37 69.88 7 50 7C30.12 7 14 12.37 14 19M19 19C19 24.25 32.88 28.5 50 28.5C67.12 28.5 81 24.25 81 19C81 13.75 67.12 9.5 50 9.5C32.88 9.5 19 13.75 19 19M14 19L14 64C14 70.63 30.12 76 50 76C69.88 76 86 70.63 86 64L86 19M14 60C14 66.63 30.12 72 50 72C69.88 72 86 66.63 86 60M24.54 72.48L22.68 94M75.46 72.48L77.32 94M50 76L50 89"
        case .kick: "M50 6C29.01 6 12 23.01 12 44C12 64.99 29.01 82 50 82C70.99 82 88 64.99 88 44C88 23.01 70.99 6 50 6M50 12C32.33 12 18 26.33 18 44C18 61.67 32.33 76 50 76C67.67 76 82 61.67 82 44C82 26.33 67.67 12 50 12M14.89 58.54L12 82M85.11 58.54L88 82"
        }
    }

    /// The solid hardware drawn under the outline: lugs, the kick's beater, the hi-hat's footboard.
    var fillPath: String? {
        switch self {
        case .hiHatClosed: nil
        case .hiHatOpen: nil
        case .hiHatPedal: "M28 96L72 85L74 92L30 99Z"
        case .crashLeft: nil
        case .crashRight: nil
        case .ride: nil
        case .cowbell: nil
        case .snare: "M19 38.2L25 38.2L24.1 61L19.9 61L19 38.2ZM47 41.6L53 41.6L52.1 64.4L47.9 64.4L47 41.6ZM75 38.2L81 38.2L80.1 61L75.9 61L75 38.2Z"
        case .sideStick: "M19 38.2L25 38.2L24.1 61L19.9 61L19 38.2ZM47 41.6L53 41.6L52.1 64.4L47.9 64.4L47 41.6ZM75 38.2L81 38.2L80.1 61L75.9 61L75 38.2Z"
        case .tom: nil
        case .floorTom: nil
        case .kick: "M52 57C52 61.97 56.03 66 61 66C65.97 66 70 61.97 70 57C70 52.03 65.97 48 61 48C56.03 48 52 52.03 52 57Z"
        }
    }

    // swiftlint:enable line_length

    /// Where a one- or two-letter label sits on the drawing, in design space — the middle of the shell band, the
    /// only part of a drum wide enough to hold a glyph at 44 pt. `nil` for everything that never carries one.
    var labelAnchor: CGPoint? {
        switch self {
        case .hiHatClosed: nil
        case .hiHatOpen: nil
        case .hiHatPedal: nil
        case .crashLeft: nil
        case .crashRight: nil
        case .ride: nil
        case .cowbell: nil
        case .snare: nil
        case .sideStick: nil
        case .tom: CGPoint(x: 50, y: 58)
        case .floorTom: CGPoint(x: 50, y: 51.5)
        case .kick: nil
        }
    }
}

// DRUM-ICON-DATA:END

/// The pictogram, square, filling whatever space it is given.
///
/// Line weight and the shell letter scale with the drawing so the whole pad reads as one set: the design reference
/// is 1.8 pt of stroke on a 38 pt icon. Sizing is left to the caller because the pad's keys share the row's width on
/// a phone, so a fixed size would overflow the narrowest ones.
struct DrumInstrumentIconView: View {
    let icon: DrumInstrumentIcon
    /// The shell letter (`H` / `M` / `L`), when the pad holds more than one drum of this kind.
    var label: String?

    @Environment(\.isEnabled) private var isEnabled

    var body: some View {
        GeometryReader { proxy in
            let side = min(proxy.size.width, proxy.size.height)
            ZStack {
                // Every layer names one fully-resolved colour. The filled hardware — the snare's lugs, the kick's
                // beater, the hi-hat's footboard — kept coming out at roughly a third opacity against a black
                // outline, and only on the pad: the same view inside the layout sheet drew it black. The pad's keys
                // are the difference. They are plain `Button`s wearing the automatic style, which restyles its
                // label, and `.primary` / `.foreground` are hierarchical — a filled shape under them can be
                // resolved a level down. `UIColor.label` is already a colour, so there is no level left to pick.
                if let fill = icon.fillPath {
                    DrumIconShape(commands: fill, viewBox: icon.viewBox).fill(ink)
                }
                DrumIconShape(commands: icon.strokePath, viewBox: icon.viewBox)
                    .stroke(ink, style: StrokeStyle(lineWidth: max(1, side * 0.047), lineCap: .round, lineJoin: .round))
                if let label, let anchor = icon.labelAnchor {
                    Text(label)
                        .font(.system(size: side * 0.28, weight: .bold))
                        .foregroundStyle(ink)
                        .position(place(anchor, in: proxy.size))
                }
            }
        }
        .aspectRatio(1, contentMode: .fit)
    }

    /// One colour for the whole drawing. The pad's key chrome dims a disabled key by dropping the foreground style
    /// to `.tertiary`; since the drawing opts out of inheriting that, it has to do the dimming itself.
    private var ink: Color {
        Color(uiColor: isEnabled ? .label : .tertiaryLabel)
    }

    /// A design-space point in the view's own coordinates. The shape scales uniformly and centres itself inside the
    /// view, so the label has to follow the same transform or it drifts off the shell as the icon resizes.
    private func place(_ point: CGPoint, in size: CGSize) -> CGPoint {
        let box = icon.viewBox
        let scale = min(size.width / box.width, size.height / box.height)
        return CGPoint(
            x: (size.width - box.width * scale) / 2 + (point.x - box.minX) * scale,
            y: (size.height - box.height * scale) / 2 + (point.y - box.minY) * scale,
        )
    }
}

/// Draws one normalized path string, mapping its view box onto the shape's rect.
private struct DrumIconShape: Shape {
    let commands: String
    let viewBox: CGRect

    func path(in rect: CGRect) -> Path {
        let scale = min(rect.width / viewBox.width, rect.height / viewBox.height)
        let originX = rect.minX + (rect.width - viewBox.width * scale) / 2
        let originY = rect.minY + (rect.height - viewBox.height * scale) / 2
        func point(_ x: Double, _ y: Double) -> CGPoint {
            CGPoint(x: originX + (x - viewBox.minX) * scale, y: originY + (y - viewBox.minY) * scale)
        }

        var path = Path()
        var numbers: [Double] = []
        var token = ""
        var command: Character?

        func flushNumber() {
            if let value = Double(token) {
                numbers.append(value)
            }
            token = ""
        }
        func flushCommand() {
            flushNumber()
            switch command {
            case "M" where numbers.count >= 2: path.move(to: point(numbers[0], numbers[1]))
            case "L" where numbers.count >= 2: path.addLine(to: point(numbers[0], numbers[1]))
            case "C" where numbers.count >= 6:
                path.addCurve(
                    to: point(numbers[4], numbers[5]),
                    control1: point(numbers[0], numbers[1]),
                    control2: point(numbers[2], numbers[3]),
                )
            case "Z": path.closeSubpath()
            default: break
            }
            numbers.removeAll(keepingCapacity: true)
        }

        for character in commands {
            if character.isLetter {
                flushCommand()
                command = character
            } else if character == " " {
                flushNumber()
            } else {
                token.append(character)
            }
        }
        flushCommand()
        return path
    }
}

#if DEBUG
#Preview("drum icons") {
    VStack(spacing: 24) {
        ForEach([CGFloat(96), 34], id: \.self) { size in
            HStack(spacing: 12) {
                ForEach(DrumInstrumentIcon.allCases, id: \.self) { icon in
                    DrumInstrumentIconView(icon: icon, label: icon == .tom ? "M" : nil)
                        .frame(height: size)
                }
            }
        }
    }
    .padding()
}
#endif
