#!/usr/bin/env bash
# Deterministic pre-release gate: verify every expected native lib is packaged in
# the APK, for every ABI, and that the wirelet-backed ones actually register their
# natives. Catches a missing/un-staged libFolino*JNI.so BEFORE the app is ever run
# (the failure otherwise only surfaces at runtime on score-open).
#
# Usage:
#   Scripts/android-release-check.sh [path/to/app.apk]
# With no arg, builds Android/app :app:assembleDebug and checks the resulting APK.
# Exits non-zero (and prints which lib/ABI is missing) if anything is absent.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd -P)"

# Source of truth — see docs/superpowers/specs/2026-06-10-android-release-crash-defenses-design.md
ABIS=("arm64-v8a" "x86_64")
EXPECTED_LIBS=(
    "libFolinoEditorJNI.so"
    "libFolinoLibraryJNI.so"
    "libFolinoReaderJNI.so"
    "libFolinoSettingsJNI.so"
    "libFolinoSoundfontJNI.so"
    "libSwiftJava.so"
)

# Libs whose Kotlin side is generated by the wirelet plugin: their natives are bound
# at load time by a plugin-emitted JNI_OnLoad/RegisterNatives, which is only emitted
# when the Gradle codegen has already written its `.wirelet-observable-jni.json`
# sidecar next to the Swift sources. Build the `.so` before Gradle in a fresh
# worktree and you get a well-formed, correctly-sized library with no JNI_OnLoad at
# all: packaging passes, and the app dies on first use with
# `UnsatisfiedLinkError: <Something>ViewModel.nativeNew`. Check the symbol, not the file.
#
# libFolinoSettingsJNI.so is deliberately absent from this list: Settings is
# jextract-only (no @WireletObservable/@WireletProvided), so its natives resolve by
# JNI name mangling and it has no JNI_OnLoad by design. libSwiftJava.so likewise.
NEEDS_JNI_ONLOAD=(
    "libFolinoEditorJNI.so"
    "libFolinoLibraryJNI.so"
    "libFolinoReaderJNI.so"
    "libFolinoSoundfontJNI.so"
)

APK="${1:-}"
if [[ -z "$APK" ]]; then
    echo "==> No APK given; building :app:assembleDebug"
    PATH="/Library/Developer/Toolchains/swift-6.3.3-RELEASE.xctoolchain/usr/bin:$PATH" \
        "$ROOT/Android/gradlew" -p "$ROOT/Android" :app:assembleDebug --no-daemon
    APK="$ROOT/Android/app/build/outputs/apk/debug/app-debug.apk"
fi

if [[ ! -f "$APK" ]]; then
    echo "error: APK not found: $APK" >&2
    exit 2
fi
echo "==> Checking native libs in: $APK"

# One listing of all packaged lib/ entries.
LIBS_IN_APK="$(unzip -Z1 "$APK" 'lib/*' 2>/dev/null || true)"

missing=0
for abi in "${ABIS[@]}"; do
    for lib in "${EXPECTED_LIBS[@]}"; do
        if ! grep -qx "lib/$abi/$lib" <<<"$LIBS_IN_APK"; then
            echo "MISSING: lib/$abi/$lib"
            missing=1
        fi
    done
done

if [[ "$missing" -ne 0 ]]; then
    echo "FAIL: one or more expected native libs are not packaged."
    exit 1
fi
echo "==> All expected native libs present for ${ABIS[*]}."

# Symbol tool: the NDK ships one, and Xcode's works on ELF too. Either is fine.
NM=""
for candidate in \
    "$(ls -d "${ANDROID_HOME:-$HOME/Library/Android/sdk}"/ndk/*/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-nm 2>/dev/null | tail -1)" \
    "$(xcrun --find llvm-nm 2>/dev/null || true)"
do
    if [[ -n "$candidate" && -x "$candidate" ]]; then
        NM="$candidate"
        break
    fi
done
if [[ -z "$NM" ]]; then
    echo "FAIL: no llvm-nm found; cannot verify JNI_OnLoad. Install the NDK or Xcode CLT." >&2
    exit 2
fi

echo "==> Checking JNI_OnLoad in the wirelet-backed libs"
EXTRACT_DIR="$(mktemp -d)"
trap 'rm -rf "$EXTRACT_DIR"' EXIT

unbound=0
for abi in "${ABIS[@]}"; do
    for lib in "${NEEDS_JNI_ONLOAD[@]}"; do
        unzip -o -q -j "$APK" "lib/$abi/$lib" -d "$EXTRACT_DIR"
        if ! "$NM" -D "$EXTRACT_DIR/$lib" 2>/dev/null | grep -q ' JNI_OnLoad$'; then
            echo "NO JNI_OnLoad: lib/$abi/$lib — built before the Gradle wirelet codegen ran."
            unbound=1
        fi
        rm -f "$EXTRACT_DIR/$lib"
    done
done

if [[ "$unbound" -ne 0 ]]; then
    echo "FAIL: a wirelet-backed lib registers no natives; the app will die on first use."
    echo "      Re-run the Gradle codegen FIRST, then Scripts/android-build-*-libs.sh, then assemble."
    exit 1
fi
echo "PASS: all expected native libs present and bound for ${ABIS[*]}."
